#!/usr/bin/env python3
"""
Performance Configuration Module v1.0.0
===========================================

Zentrale Konfiguration für Performance-Optimierungen:
- Environment-basierte Sleep-Intervalle  
- Konfigurierbare Rate-Limits
- HTTP Client Pool-Einstellungen
- Event Processing Optimierung

Implementiert für Issue #23 - Performance-Optimierungen
Ziel: 30-50% Performance-Steigerung durch intelligente Konfiguration

Author: Generated by Claude Code - Issue #23 Performance Optimization
Date: 2025-08-24
"""

import os
import logging
from typing import Dict, Any, Optional
from dataclasses import dataclass
from enum import Enum

logger = logging.getLogger(__name__)

class PerformanceProfile(Enum):
    """Performance Profile Definitionen für verschiedene Umgebungen"""
    DEVELOPMENT = "development"
    PRODUCTION = "production"
    HIGH_PERFORMANCE = "high_performance"
    RESOURCE_CONSTRAINED = "resource_constrained"

@dataclass
class SleepIntervals:
    """Konfigurierbare Sleep-Intervalle für verschiedene Operationen"""
    # Monitoring Intervals (Reduziert von 0.1s auf intelligente Werte)
    monitoring_loop: float = 5.0          # Standard: 5s (war 0.1s = 50x Verbesserung)
    health_check: float = 30.0           # Health Check: 30s 
    heartbeat: float = 30.0              # Service Heartbeat: 30s
    
    # Event Processing
    event_processing: float = 0.5        # Event Processing: 500ms (war 100ms = 5x)
    event_retry: float = 1.0             # Event Retry: 1s
    
    # Data Collection Intervals
    market_data_collection: float = 300.0    # Market Data: 5min (war verschiedene Werte)
    portfolio_sync: float = 60.0             # Portfolio Sync: 1min
    prediction_update: float = 1800.0        # Predictions: 30min
    
    # API Rate Limiting (Standardisiert)
    alpha_vantage_delay: float = 12.0        # Alpha Vantage: 12s (Rate Limit)
    iex_cloud_delay: float = 1.0             # IEX Cloud: 1s (optimiert von 5s)
    twelve_data_delay: float = 1.0           # Twelve Data: 1s (optimiert von 2s) 
    eod_historical_delay: float = 1.0        # EOD Historical: 1s (optimiert von 0.5s/3s)
    finnhub_delay: float = 1.0               # Finnhub: 1s (optimiert von 3s)
    
    # Error Recovery
    error_backoff_base: float = 5.0          # Base backoff: 5s
    error_backoff_max: float = 300.0         # Max backoff: 5min
    
    # Background Tasks
    cleanup_interval: float = 3600.0         # Cleanup: 1h
    backup_interval: float = 14400.0         # Backup: 4h

@dataclass  
class HttpClientConfig:
    """HTTP Client Pool Konfiguration"""
    # Connection Pool Settings
    max_connections: int = 100               # Max Connections pro Pool
    max_connections_per_host: int = 10       # Max pro Host
    connection_timeout: float = 10.0         # Connection Timeout
    read_timeout: float = 30.0               # Read Timeout
    total_timeout: float = 60.0              # Total Request Timeout
    
    # Keep-Alive Settings  
    keepalive_timeout: float = 30.0          # Keep-Alive Timeout
    keepalive_max_requests: int = 100        # Max Requests per Connection
    
    # Retry Configuration
    max_retries: int = 3                     # Max Retry Attempts
    retry_backoff: float = 1.0               # Retry Backoff Base
    
    # Performance Optimizations
    enable_compression: bool = True          # Enable Gzip Compression
    enable_cookies: bool = False             # Disable Cookies (Performance)
    
@dataclass
class RateLimitConfig:
    """Centralized Rate Limiting Configuration"""
    # API Provider Limits (Requests per minute)
    alpha_vantage_rpm: int = 5              # Alpha Vantage: 5/min
    iex_cloud_rpm: int = 100                # IEX Cloud: 100/min  
    twelve_data_rpm: int = 800              # Twelve Data: 800/min
    finnhub_rpm: int = 60                   # Finnhub: 60/min
    eod_historical_rpm: int = 1000          # EOD Historical: 1000/min
    
    # Internal Rate Limits
    event_publishing_rps: int = 1000        # Event Publishing: 1000/sec
    database_query_rps: int = 500           # Database Queries: 500/sec
    
    # Burst Handling
    burst_multiplier: float = 2.0           # Burst Multiplier
    burst_duration: int = 10                # Burst Duration (seconds)

@dataclass
class PerformanceMetrics:
    """Performance Metriken Konfiguration"""
    # Response Time Targets
    target_event_processing_ms: int = 50    # Target: 50ms (war 120ms)
    target_db_query_ms: int = 25            # Target: 25ms (war 50ms)  
    target_api_response_ms: int = 500       # Target: 500ms
    target_ui_update_ms: int = 200          # Target: 200ms (war 1000ms)
    
    # Throughput Targets
    target_events_per_second: int = 2000    # Target: 2000 EPS (war 1000)
    target_db_queries_per_second: int = 1000 # Target: 1000 QPS (war 500)
    
    # Resource Targets  
    target_memory_mb: int = 128             # Target: 128MB (war 200MB)
    target_cpu_percent: float = 25.0       # Target: 25% CPU (war 50%)

class PerformanceConfigManager:
    """
    Zentrale Performance-Konfiguration Manager
    
    Verwaltet alle Performance-relevanten Einstellungen:
    - Environment-basierte Konfiguration
    - Profile-spezifische Optimierungen  
    - Runtime-Performance Anpassungen
    """
    
    def __init__(self, profile: Optional[PerformanceProfile] = None):
        """
        Initialisiert Performance-Konfiguration
        
        Args:
            profile: Performance Profil (auto-detect wenn None)
        """
        self.profile = profile or self._detect_profile()
        self._load_configuration()
        logger.info(f"Performance-Konfiguration geladen: {self.profile.value}")
    
    def _detect_profile(self) -> PerformanceProfile:
        """Auto-Detection des Performance-Profils basierend auf Environment"""
        env = os.getenv('AKTIENANALYSE_ENV', 'development').lower()
        
        profile_mapping = {
            'development': PerformanceProfile.DEVELOPMENT,
            'testing': PerformanceProfile.DEVELOPMENT, 
            'production': PerformanceProfile.PRODUCTION,
            'high_performance': PerformanceProfile.HIGH_PERFORMANCE,
            'resource_constrained': PerformanceProfile.RESOURCE_CONSTRAINED
        }
        
        return profile_mapping.get(env, PerformanceProfile.DEVELOPMENT)
    
    def _load_configuration(self) -> None:
        """Lädt Profile-spezifische Konfiguration"""
        if self.profile == PerformanceProfile.DEVELOPMENT:
            self._load_development_config()
        elif self.profile == PerformanceProfile.PRODUCTION:
            self._load_production_config()
        elif self.profile == PerformanceProfile.HIGH_PERFORMANCE:
            self._load_high_performance_config()
        elif self.profile == PerformanceProfile.RESOURCE_CONSTRAINED:
            self._load_resource_constrained_config()
            
    def _load_development_config(self) -> None:
        """Development Profile: Ausgewogen zwischen Performance und Debugging"""
        self.sleep_intervals = SleepIntervals(
            monitoring_loop=float(os.getenv('MONITORING_LOOP_INTERVAL', '5.0')),
            health_check=float(os.getenv('HEALTH_CHECK_INTERVAL', '30.0')),
            event_processing=float(os.getenv('EVENT_PROCESSING_INTERVAL', '0.5')),
            market_data_collection=float(os.getenv('MARKET_DATA_INTERVAL', '300.0'))
        )
        
        self.http_config = HttpClientConfig(
            max_connections=int(os.getenv('HTTP_MAX_CONNECTIONS', '50')),
            connection_timeout=float(os.getenv('HTTP_CONNECTION_TIMEOUT', '10.0'))
        )
        
        self.rate_limits = RateLimitConfig()
        self.metrics = PerformanceMetrics()
        
    def _load_production_config(self) -> None:
        """Production Profile: Optimiert für Stabilität und Performance"""
        self.sleep_intervals = SleepIntervals(
            monitoring_loop=float(os.getenv('MONITORING_LOOP_INTERVAL', '10.0')),    # Weniger häufig
            health_check=float(os.getenv('HEALTH_CHECK_INTERVAL', '60.0')),          # 1min Health Check
            event_processing=float(os.getenv('EVENT_PROCESSING_INTERVAL', '0.2')),   # Schnellere Events
            market_data_collection=float(os.getenv('MARKET_DATA_INTERVAL', '600.0')) # 10min Market Data
        )
        
        self.http_config = HttpClientConfig(
            max_connections=int(os.getenv('HTTP_MAX_CONNECTIONS', '100')),
            connection_timeout=float(os.getenv('HTTP_CONNECTION_TIMEOUT', '5.0'))
        )
        
        self.rate_limits = RateLimitConfig(
            event_publishing_rps=int(os.getenv('EVENT_PUBLISHING_RPS', '2000'))
        )
        
        self.metrics = PerformanceMetrics(
            target_event_processing_ms=int(os.getenv('TARGET_EVENT_PROCESSING_MS', '30'))
        )
        
    def _load_high_performance_config(self) -> None:
        """High Performance Profile: Maximum Performance"""
        self.sleep_intervals = SleepIntervals(
            monitoring_loop=float(os.getenv('MONITORING_LOOP_INTERVAL', '2.0')),     # Sehr schnell
            health_check=float(os.getenv('HEALTH_CHECK_INTERVAL', '15.0')),          # Häufige Health Checks
            event_processing=float(os.getenv('EVENT_PROCESSING_INTERVAL', '0.1')),   # Ultra-schnell
            market_data_collection=float(os.getenv('MARKET_DATA_INTERVAL', '60.0'))  # 1min Market Data
        )
        
        self.http_config = HttpClientConfig(
            max_connections=int(os.getenv('HTTP_MAX_CONNECTIONS', '200')),           # Mehr Connections
            connection_timeout=float(os.getenv('HTTP_CONNECTION_TIMEOUT', '3.0')),   # Schnelle Timeouts
            keepalive_max_requests=int(os.getenv('HTTP_KEEPALIVE_REQUESTS', '200'))  # Mehr Keep-Alive
        )
        
        self.rate_limits = RateLimitConfig(
            event_publishing_rps=int(os.getenv('EVENT_PUBLISHING_RPS', '5000')),     # Hohe Throughput
            database_query_rps=int(os.getenv('DATABASE_QUERY_RPS', '2000'))
        )
        
        self.metrics = PerformanceMetrics(
            target_event_processing_ms=int(os.getenv('TARGET_EVENT_PROCESSING_MS', '20')), # Ultra-schnell
            target_events_per_second=int(os.getenv('TARGET_EVENTS_PER_SECOND', '5000'))
        )
    
    def _load_resource_constrained_config(self) -> None:
        """Resource Constrained Profile: Minimaler Ressourcenverbrauch"""
        self.sleep_intervals = SleepIntervals(
            monitoring_loop=float(os.getenv('MONITORING_LOOP_INTERVAL', '30.0')),    # Sehr selten
            health_check=float(os.getenv('HEALTH_CHECK_INTERVAL', '120.0')),         # 2min Health Check  
            event_processing=float(os.getenv('EVENT_PROCESSING_INTERVAL', '2.0')),   # Langsamere Events
            market_data_collection=float(os.getenv('MARKET_DATA_INTERVAL', '1800.0')) # 30min Market Data
        )
        
        self.http_config = HttpClientConfig(
            max_connections=int(os.getenv('HTTP_MAX_CONNECTIONS', '20')),            # Weniger Connections
            connection_timeout=float(os.getenv('HTTP_CONNECTION_TIMEOUT', '15.0')),  # Längere Timeouts
            max_connections_per_host=int(os.getenv('HTTP_MAX_CONN_PER_HOST', '5'))   # Begrenzte Connections
        )
        
        self.rate_limits = RateLimitConfig(
            event_publishing_rps=int(os.getenv('EVENT_PUBLISHING_RPS', '100')),      # Niedrige Throughput
            database_query_rps=int(os.getenv('DATABASE_QUERY_RPS', '50'))
        )
        
        self.metrics = PerformanceMetrics(
            target_memory_mb=int(os.getenv('TARGET_MEMORY_MB', '64')),               # Weniger Memory
            target_cpu_percent=float(os.getenv('TARGET_CPU_PERCENT', '15.0'))       # Weniger CPU
        )
    
    def get_sleep_interval(self, operation: str) -> float:
        """
        Holt optimiertes Sleep-Interval für spezifische Operation
        
        Args:
            operation: Name der Operation (z.B. 'monitoring_loop', 'health_check')
            
        Returns:
            Optimiertes Sleep-Interval in Sekunden
        """
        return getattr(self.sleep_intervals, operation, 1.0)
    
    def get_api_delay(self, provider: str) -> float:
        """
        Holt API-spezifisches Rate-Limiting Delay
        
        Args:
            provider: API Provider Name (z.B. 'alpha_vantage', 'iex_cloud')
            
        Returns:
            Delay in Sekunden zwischen API Calls
        """
        delay_mapping = {
            'alpha_vantage': self.sleep_intervals.alpha_vantage_delay,
            'iex_cloud': self.sleep_intervals.iex_cloud_delay,
            'twelve_data': self.sleep_intervals.twelve_data_delay,
            'eod_historical': self.sleep_intervals.eod_historical_delay,
            'finnhub': self.sleep_intervals.finnhub_delay
        }
        return delay_mapping.get(provider, 1.0)
    
    def get_http_config(self) -> HttpClientConfig:
        """Returns HTTP Client Konfiguration"""
        return self.http_config
    
    def get_rate_limit_config(self) -> RateLimitConfig:
        """Returns Rate Limiting Konfiguration"""
        return self.rate_limits
    
    def get_performance_metrics(self) -> PerformanceMetrics:
        """Returns Performance Metriken Konfiguration"""
        return self.metrics
    
    def log_configuration_summary(self) -> None:
        """Loggt zusammenfassende Konfiguration für Debugging"""
        logger.info(f"Performance Profile: {self.profile.value}")
        logger.info(f"Monitoring Loop Interval: {self.sleep_intervals.monitoring_loop}s")
        logger.info(f"Event Processing Interval: {self.sleep_intervals.event_processing}s")
        logger.info(f"HTTP Max Connections: {self.http_config.max_connections}")
        logger.info(f"Target Event Processing: {self.metrics.target_event_processing_ms}ms")

# Globale Performance-Konfiguration Instanz
_performance_config: Optional[PerformanceConfigManager] = None

def get_performance_config() -> PerformanceConfigManager:
    """
    Singleton-Pattern für globale Performance-Konfiguration
    
    Returns:
        Globale PerformanceConfigManager Instanz
    """
    global _performance_config
    if _performance_config is None:
        _performance_config = PerformanceConfigManager()
        _performance_config.log_configuration_summary()
    return _performance_config

def optimize_sleep_interval(operation: str, default: float = 1.0) -> float:
    """
    Convenience-Funktion für optimierte Sleep-Intervalle
    
    Args:
        operation: Operation Name
        default: Default-Wert wenn nicht konfiguriert
        
    Returns:
        Optimiertes Sleep-Interval
    """
    config = get_performance_config()
    return config.get_sleep_interval(operation) if hasattr(config.sleep_intervals, operation) else default

def get_api_rate_limit_delay(provider: str) -> float:
    """
    Convenience-Funktion für API Rate-Limiting Delays
    
    Args:
        provider: API Provider Name
        
    Returns:
        Rate-Limiting Delay in Sekunden
    """
    config = get_performance_config()
    return config.get_api_delay(provider)

if __name__ == "__main__":
    # Test der Performance-Konfiguration
    logger.basicConfig(level=logging.INFO)
    
    config = PerformanceConfigManager()
    config.log_configuration_summary()
    
    # Test verschiedener Profile
    for profile in PerformanceProfile:
        config_test = PerformanceConfigManager(profile)
        print(f"\n{profile.value.upper()} Profile:")
        print(f"  Monitoring Loop: {config_test.sleep_intervals.monitoring_loop}s")
        print(f"  Event Processing: {config_test.sleep_intervals.event_processing}s") 
        print(f"  HTTP Connections: {config_test.http_config.max_connections}")