#!/usr/bin/env python3
"""
Performance Monitor v1.0.0
===========================

Performance-Monitoring und Metriken für Issue #23 Optimierungen:
- Response Time Monitoring
- Resource Usage Tracking  
- API Rate-Limiting Überwachung
- HTTP Client Pool Performance
- Event Processing Throughput

Implementiert für Issue #23 - Performance-Optimierungen
Performance-Ziel: Real-time Performance-Validierung der Optimierungen

Author: Generated by Claude Code - Issue #23 Performance Optimization
Date: 2025-08-24
"""

import time
import asyncio
import logging
import psutil
import json
from datetime import datetime, timedelta
from typing import Dict, Any, List, Optional, Callable
from dataclasses import dataclass, field
from contextlib import asynccontextmanager
import statistics

logger = logging.getLogger(__name__)

@dataclass
class PerformanceMetric:
    """Performance Metrik Definition"""
    name: str
    value: float
    unit: str
    timestamp: datetime
    category: str
    target: Optional[float] = None
    
    @property
    def is_within_target(self) -> bool:
        """Prüft ob Metrik innerhalb des Zielwerts ist"""
        return self.target is None or self.value <= self.target

@dataclass
class PerformanceSummary:
    """Performance Summary für Zeitraum"""
    start_time: datetime
    end_time: datetime
    metrics: Dict[str, List[PerformanceMetric]] = field(default_factory=dict)
    
    @property
    def duration_seconds(self) -> float:
        return (self.end_time - self.start_time).total_seconds()
    
    def get_metric_stats(self, metric_name: str) -> Dict[str, float]:
        """Berechnet Statistiken für Metrik"""
        if metric_name not in self.metrics or not self.metrics[metric_name]:
            return {}
        
        values = [m.value for m in self.metrics[metric_name]]
        return {
            'count': len(values),
            'min': min(values),
            'max': max(values),
            'avg': statistics.mean(values),
            'median': statistics.median(values),
            'std_dev': statistics.stdev(values) if len(values) > 1 else 0.0
        }

class PerformanceTimer:
    """
    Context Manager für Performance-Zeit-Messung
    """
    
    def __init__(self, operation_name: str, monitor: 'PerformanceMonitor'):
        self.operation_name = operation_name
        self.monitor = monitor
        self.start_time = None
        
    def __enter__(self):
        self.start_time = time.perf_counter()
        return self
        
    def __exit__(self, exc_type, exc_val, exc_tb):
        if self.start_time:
            duration_ms = (time.perf_counter() - self.start_time) * 1000
            self.monitor.record_response_time(self.operation_name, duration_ms)

class PerformanceMonitor:
    """
    Zentraler Performance Monitor
    
    Überwacht und sammelt Performance-Metriken:
    - Response Times (Target: <50ms Event Processing)
    - Resource Usage (Target: <150MB Memory)
    - Throughput (Target: 2000 Events/sec)
    - API Rate-Limiting Effizienz
    """
    
    def __init__(self, max_metrics_per_type: int = 1000):
        self.max_metrics_per_type = max_metrics_per_type
        self.metrics: Dict[str, List[PerformanceMetric]] = {}
        self.start_time = datetime.now()
        self._lock = asyncio.Lock()
        
        # Performance Targets (aus Performance Config)
        self.targets = {
            'event_processing_ms': 50.0,
            'db_query_ms': 25.0,
            'api_response_ms': 500.0,
            'memory_mb': 150.0,
            'cpu_percent': 25.0,
            'events_per_second': 2000.0
        }
        
        logger.info("Performance Monitor initialisiert", targets=self.targets)
    
    def record_metric(self, name: str, value: float, unit: str, category: str = 'general'):
        """
        Registriert Performance-Metrik
        
        Args:
            name: Metrik Name
            value: Metrik Wert
            unit: Einheit (ms, mb, percent, count, etc.)
            category: Kategorie (response_time, resource, throughput, etc.)
        """
        metric = PerformanceMetric(
            name=name,
            value=value,
            unit=unit,
            timestamp=datetime.now(),
            category=category,
            target=self.targets.get(name)
        )
        
        if name not in self.metrics:
            self.metrics[name] = []
        
        self.metrics[name].append(metric)
        
        # Begrenze Anzahl Metriken pro Typ (Memory Management)
        if len(self.metrics[name]) > self.max_metrics_per_type:
            self.metrics[name] = self.metrics[name][-self.max_metrics_per_type:]
        
        # Log kritische Performance-Probleme
        if not metric.is_within_target:
            logger.warning(f"Performance target exceeded: {name} = {value}{unit} (target: {metric.target}{unit})")
    
    def record_response_time(self, operation: str, duration_ms: float):
        """Registriert Response Time Metrik"""
        self.record_metric(f"{operation}_response_ms", duration_ms, "ms", "response_time")
    
    def record_throughput(self, operation: str, count: int, duration_seconds: float):
        """Registriert Throughput Metrik"""
        throughput = count / duration_seconds if duration_seconds > 0 else 0
        self.record_metric(f"{operation}_per_second", throughput, "ops/sec", "throughput")
    
    def record_resource_usage(self):
        """Sammelt aktuelle Resource Usage Metriken"""
        try:
            # CPU Usage
            cpu_percent = psutil.cpu_percent(interval=0.1)
            self.record_metric("cpu_percent", cpu_percent, "%", "resource")
            
            # Memory Usage
            process = psutil.Process()
            memory_mb = process.memory_info().rss / 1024 / 1024
            self.record_metric("memory_mb", memory_mb, "MB", "resource")
            
            # System Memory
            system_memory = psutil.virtual_memory()
            self.record_metric("system_memory_percent", system_memory.percent, "%", "resource")
            
        except Exception as e:
            logger.error(f"Error recording resource usage: {e}")
    
    def get_recent_metrics(self, metric_name: str, minutes: int = 5) -> List[PerformanceMetric]:
        """Holt recent Metriken für spezifischen Namen"""
        if metric_name not in self.metrics:
            return []
        
        cutoff_time = datetime.now() - timedelta(minutes=minutes)
        return [
            metric for metric in self.metrics[metric_name]
            if metric.timestamp >= cutoff_time
        ]
    
    def get_performance_summary(self, minutes: int = 60) -> PerformanceSummary:
        """
        Erstellt Performance Summary für Zeitraum
        
        Args:
            minutes: Zeitraum in Minuten
            
        Returns:
            PerformanceSummary mit aggregierten Metriken
        """
        end_time = datetime.now()
        start_time = end_time - timedelta(minutes=minutes)
        
        summary = PerformanceSummary(start_time=start_time, end_time=end_time)
        
        for metric_name, metric_list in self.metrics.items():
            recent_metrics = [
                m for m in metric_list
                if start_time <= m.timestamp <= end_time
            ]
            if recent_metrics:
                summary.metrics[metric_name] = recent_metrics
        
        return summary
    
    def get_health_status(self) -> Dict[str, Any]:
        """
        Returns Performance Health Status
        
        Returns:
            Health Dictionary mit Performance-Bewertung
        """
        summary = self.get_performance_summary(minutes=10)
        
        health_status = {
            'overall_health': 'healthy',
            'timestamp': datetime.now().isoformat(),
            'monitoring_duration_hours': (datetime.now() - self.start_time).total_seconds() / 3600,
            'metrics_count': sum(len(metrics) for metrics in self.metrics.values()),
            'categories': {}
        }
        
        # Bewerte jede Kategorie
        categories = set(m.category for metrics in summary.metrics.values() for m in metrics)
        
        for category in categories:
            category_metrics = [
                m for metrics in summary.metrics.values() 
                for m in metrics if m.category == category
            ]
            
            if not category_metrics:
                continue
            
            # Prüfe Target-Compliance
            target_violations = [m for m in category_metrics if not m.is_within_target]
            compliance_rate = 1 - (len(target_violations) / len(category_metrics))
            
            category_health = 'healthy' if compliance_rate >= 0.9 else 'warning' if compliance_rate >= 0.7 else 'critical'
            
            health_status['categories'][category] = {
                'health': category_health,
                'metrics_count': len(category_metrics),
                'target_compliance_rate': round(compliance_rate * 100, 1),
                'violations': len(target_violations)
            }
            
            # Overall Health basierend auf schlechtester Kategorie
            if category_health == 'critical':
                health_status['overall_health'] = 'critical'
            elif category_health == 'warning' and health_status['overall_health'] != 'critical':
                health_status['overall_health'] = 'warning'
        
        return health_status
    
    def timer(self, operation_name: str) -> PerformanceTimer:
        """
        Returns Performance Timer Context Manager
        
        Example:
            with monitor.timer('event_processing'):
                await process_event()
        """
        return PerformanceTimer(operation_name, self)
    
    async def continuous_resource_monitoring(self, interval_seconds: int = 30):
        """
        Continuous Resource Usage Monitoring
        
        Args:
            interval_seconds: Monitoring Intervall
        """
        logger.info(f"Starting continuous resource monitoring (interval: {interval_seconds}s)")
        
        try:
            while True:
                self.record_resource_usage()
                await asyncio.sleep(interval_seconds)
        except asyncio.CancelledError:
            logger.info("Continuous resource monitoring stopped")
        except Exception as e:
            logger.error(f"Error in continuous resource monitoring: {e}")
    
    def export_metrics(self, filepath: str, format: str = 'json'):
        """
        Exportiert Performance-Metriken
        
        Args:
            filepath: Export-Dateipfad
            format: Export-Format ('json', 'csv')
        """
        try:
            summary = self.get_performance_summary(minutes=24*60)  # 24 Stunden
            
            if format.lower() == 'json':
                export_data = {
                    'export_timestamp': datetime.now().isoformat(),
                    'monitoring_duration_hours': summary.duration_seconds / 3600,
                    'performance_summary': {
                        metric_name: {
                            'stats': summary.get_metric_stats(metric_name),
                            'recent_values': [
                                {
                                    'value': m.value,
                                    'timestamp': m.timestamp.isoformat(),
                                    'within_target': m.is_within_target
                                } for m in metrics[-100:]  # Letzte 100 Werte
                            ]
                        } for metric_name, metrics in summary.metrics.items()
                    },
                    'health_status': self.get_health_status()
                }
                
                with open(filepath, 'w') as f:
                    json.dump(export_data, f, indent=2, default=str)
                    
                logger.info(f"Performance metrics exported to {filepath}")
                
        except Exception as e:
            logger.error(f"Error exporting metrics: {e}")

# Globale Performance Monitor Instanz
_performance_monitor: Optional[PerformanceMonitor] = None

def get_performance_monitor() -> PerformanceMonitor:
    """
    Singleton für globalen Performance Monitor
    
    Returns:
        PerformanceMonitor Instanz
    """
    global _performance_monitor
    if _performance_monitor is None:
        _performance_monitor = PerformanceMonitor()
    return _performance_monitor

@asynccontextmanager
async def monitor_performance(operation_name: str):
    """
    Context Manager für Performance-Monitoring
    
    Args:
        operation_name: Name der Operation
        
    Example:
        async with monitor_performance('database_query'):
            result = await db.query(sql)
    """
    monitor = get_performance_monitor()
    with monitor.timer(operation_name):
        yield monitor

def record_performance_metric(name: str, value: float, unit: str, category: str = 'general'):
    """
    Convenience-Funktion für Metrik-Recording
    
    Args:
        name: Metrik Name
        value: Wert
        unit: Einheit
        category: Kategorie
    """
    monitor = get_performance_monitor()
    monitor.record_metric(name, value, unit, category)

async def start_performance_monitoring(interval_seconds: int = 30) -> asyncio.Task:
    """
    Startet kontinuierliches Performance-Monitoring
    
    Args:
        interval_seconds: Monitoring-Intervall
        
    Returns:
        AsyncIO Task für Monitoring
    """
    monitor = get_performance_monitor()
    task = asyncio.create_task(monitor.continuous_resource_monitoring(interval_seconds))
    logger.info("Performance monitoring task started")
    return task

if __name__ == "__main__":
    # Test der Performance-Monitoring
    import asyncio
    
    async def test_performance_monitoring():
        print("Testing Performance Monitoring...")
        
        monitor = PerformanceMonitor()
        
        # Simuliere verschiedene Performance-Metriken
        for i in range(100):
            # Response Times (verschiedene Performance-Level)
            if i < 50:
                monitor.record_response_time('event_processing', 30.0 + i * 0.5)  # Gut
            else:
                monitor.record_response_time('event_processing', 60.0 + i * 1.0)  # Schlecht
            
            # Resource Usage
            monitor.record_metric('memory_mb', 120 + i * 2, 'MB', 'resource')
            
            # Throughput
            monitor.record_metric('events_per_second', 2500 - i * 10, 'ops/sec', 'throughput')
            
            await asyncio.sleep(0.01)  # Simuliere Zeit
        
        # Performance Summary
        summary = monitor.get_performance_summary(minutes=1)
        for metric_name in summary.metrics:
            stats = summary.get_metric_stats(metric_name)
            print(f"{metric_name}: avg={stats['avg']:.1f}, min={stats['min']:.1f}, max={stats['max']:.1f}")
        
        # Health Status
        health = monitor.get_health_status()
        print(f"\nOverall Health: {health['overall_health']}")
        for category, status in health['categories'].items():
            print(f"  {category}: {status['health']} (compliance: {status['target_compliance_rate']}%)")
        
        # Export Test
        monitor.export_metrics('/tmp/performance_test.json')
        print("Performance metrics exported to /tmp/performance_test.json")
    
    asyncio.run(test_performance_monitoring())