#!/usr/bin/env python3
"""
Centralized Rate Limiter Service v1.0.0
========================================

Unified Rate-Limiting für alle External APIs und Services:
- Intelligent Rate Limiting basierend auf API-Provider
- Token Bucket Algorithm für Burst-Handling
- Cross-Service Rate-Limiting Koordination
- Performance-Optimierte Redis-basierte Implementation

Implementiert für Issue #23 - Performance-Optimierungen
Performance-Ziel: Harmonisierte Rate-Limiting für optimale API Throughput

Author: Generated by Claude Code - Issue #23 Performance Optimization
Date: 2025-08-24
"""

import asyncio
import time
import logging
from typing import Dict, Optional, List, Tuple, Union
from dataclasses import dataclass, field
from enum import Enum
import json
import aioredis
from contextlib import asynccontextmanager

from .performance_config_v1_0_0_20250824 import get_performance_config, RateLimitConfig

logger = logging.getLogger(__name__)

class RateLimitStrategy(Enum):
    """Rate-Limiting Strategien"""
    TOKEN_BUCKET = "token_bucket"       # Token Bucket für Burst-Handling
    SLIDING_WINDOW = "sliding_window"   # Sliding Window für gleichmäßige Rate
    FIXED_WINDOW = "fixed_window"       # Fixed Window für einfache Limits
    ADAPTIVE = "adaptive"               # Adaptive basierend auf Response Times

@dataclass
class RateLimitRule:
    """Rate-Limiting Regel Definition"""
    name: str
    requests_per_minute: int
    burst_multiplier: float = 2.0
    strategy: RateLimitStrategy = RateLimitStrategy.TOKEN_BUCKET
    priority: int = 0  # Höhere Priorität = wichtigere Requests
    backoff_factor: float = 1.0
    max_backoff: float = 300.0  # 5 Minuten maximum backoff
    
    def __post_init__(self):
        self.requests_per_second = self.requests_per_minute / 60.0
        self.token_refill_interval = 1.0 / self.requests_per_second if self.requests_per_second > 0 else 1.0
        self.max_tokens = int(self.requests_per_minute * self.burst_multiplier)

@dataclass 
class RateLimitResult:
    """Result einer Rate-Limiting Prüfung"""
    allowed: bool
    tokens_remaining: int
    reset_time: float
    retry_after: Optional[float] = None
    backoff_duration: Optional[float] = None

class TokenBucket:
    """
    Token Bucket Implementation für Rate-Limiting
    Ermöglicht Burst-Requests bis zur definierten Kapazität
    """
    
    def __init__(self, rule: RateLimitRule):
        self.rule = rule
        self.tokens = rule.max_tokens
        self.last_refill = time.time()
        self.consecutive_denials = 0
        
    def try_consume(self, tokens: int = 1) -> Tuple[bool, int, float]:
        """
        Versucht Tokens zu konsumieren
        
        Args:
            tokens: Anzahl zu konsumierender Tokens
            
        Returns:
            Tuple[allowed, remaining_tokens, next_refill_time]
        """
        now = time.time()
        self._refill_tokens(now)
        
        if self.tokens >= tokens:
            self.tokens -= tokens
            self.consecutive_denials = 0
            return True, self.tokens, now + self.rule.token_refill_interval
        else:
            self.consecutive_denials += 1
            retry_after = (tokens - self.tokens) * self.rule.token_refill_interval
            return False, self.tokens, now + retry_after
    
    def _refill_tokens(self, now: float):
        """Füllt Tokens basierend auf verstrichener Zeit auf"""
        elapsed = now - self.last_refill
        tokens_to_add = elapsed * self.rule.requests_per_second
        
        self.tokens = min(self.rule.max_tokens, self.tokens + tokens_to_add)
        self.last_refill = now
    
    def get_backoff_duration(self) -> float:
        """Berechnet Backoff-Duration basierend auf aufeinanderfolgenden Denials"""
        if self.consecutive_denials == 0:
            return 0.0
            
        backoff = min(
            self.rule.backoff_factor * (2 ** (self.consecutive_denials - 1)),
            self.rule.max_backoff
        )
        return backoff

class RateLimiterService:
    """
    Zentraler Rate-Limiting Service
    
    Verwaltet Rate-Limits für verschiedene APIs und Services mit:
    - Token Bucket Algorithm für Burst-Handling
    - Redis-basierte Persistierung für Cross-Process Coordination
    - Intelligente Backoff-Strategien
    - Performance-Monitoring und Anpassungen
    """
    
    def __init__(self, redis_client: Optional[aioredis.Redis] = None):
        self.redis_client = redis_client
        self.local_buckets: Dict[str, TokenBucket] = {}
        self.rate_limit_config = get_performance_config().get_rate_limit_config()
        self._rules: Dict[str, RateLimitRule] = {}
        self._lock = asyncio.Lock()
        self._initialize_default_rules()
        logger.info("Rate Limiter Service initialisiert")
    
    async def initialize(self, redis_url: str = "redis://localhost:6379"):
        """Initialisiert Redis-Connection für distributed rate limiting"""
        if self.redis_client is None:
            self.redis_client = aioredis.from_url(redis_url)
            
        await self._register_service()
        logger.info("Rate Limiter Service mit Redis initialisiert")
    
    def _initialize_default_rules(self):
        """Initialisiert Standard Rate-Limiting Regeln für bekannte APIs"""
        # API Provider Rate Limits (aus Performance Config)
        api_rules = {
            'alpha_vantage': RateLimitRule(
                name='alpha_vantage',
                requests_per_minute=self.rate_limit_config.alpha_vantage_rpm,
                burst_multiplier=1.0,  # Keine Bursts für Alpha Vantage
                backoff_factor=2.0,
                priority=1
            ),
            'iex_cloud': RateLimitRule(
                name='iex_cloud', 
                requests_per_minute=self.rate_limit_config.iex_cloud_rpm,
                burst_multiplier=1.5,
                priority=2
            ),
            'twelve_data': RateLimitRule(
                name='twelve_data',
                requests_per_minute=self.rate_limit_config.twelve_data_rpm,
                burst_multiplier=2.0,
                priority=2
            ),
            'finnhub': RateLimitRule(
                name='finnhub',
                requests_per_minute=self.rate_limit_config.finnhub_rpm,
                burst_multiplier=1.2,
                priority=2
            ),
            'eod_historical': RateLimitRule(
                name='eod_historical',
                requests_per_minute=self.rate_limit_config.eod_historical_rpm,
                burst_multiplier=3.0,  # Hohe Kapazität
                priority=3
            ),
            # Internal Service Rate Limits
            'event_publishing': RateLimitRule(
                name='event_publishing',
                requests_per_minute=self.rate_limit_config.event_publishing_rps * 60,
                burst_multiplier=self.rate_limit_config.burst_multiplier,
                strategy=RateLimitStrategy.SLIDING_WINDOW,
                priority=10  # Höchste Priorität
            ),
            'database_queries': RateLimitRule(
                name='database_queries',
                requests_per_minute=self.rate_limit_config.database_query_rps * 60,
                burst_multiplier=self.rate_limit_config.burst_multiplier,
                strategy=RateLimitStrategy.SLIDING_WINDOW,
                priority=9
            )
        }
        
        self._rules.update(api_rules)
        
        # Initialisiere lokale Token Buckets
        for rule in self._rules.values():
            self.local_buckets[rule.name] = TokenBucket(rule)
    
    async def _register_service(self):
        """Registriert Service bei Redis für Koordination"""
        if self.redis_client:
            service_info = {
                'instance_id': f"{time.time()}",
                'rules': [rule.name for rule in self._rules.values()],
                'started_at': time.time()
            }
            await self.redis_client.setex(
                'rate_limiter:service:info',
                3600,  # 1 hour TTL
                json.dumps(service_info)
            )
    
    async def check_rate_limit(self, 
                               rule_name: str, 
                               tokens: int = 1,
                               client_id: Optional[str] = None) -> RateLimitResult:
        """
        Prüft Rate Limit für spezifische Regel
        
        Args:
            rule_name: Name der Rate-Limiting Regel
            tokens: Anzahl zu konsumierender Tokens (Default: 1)
            client_id: Optional Client-ID für per-client limiting
            
        Returns:
            RateLimitResult mit Erlaubnis und verbleibenden Tokens
        """
        if rule_name not in self._rules:
            # Unknown rule - allow with warning
            logger.warning(f"Unknown rate limit rule: {rule_name}")
            return RateLimitResult(allowed=True, tokens_remaining=1000, reset_time=time.time() + 60)
        
        rule = self._rules[rule_name]
        bucket_key = f"{rule_name}:{client_id}" if client_id else rule_name
        
        # Redis-based distributed rate limiting (wenn verfügbar)
        if self.redis_client:
            return await self._check_distributed_rate_limit(bucket_key, rule, tokens)
        else:
            # Fallback auf lokale Token Buckets
            return await self._check_local_rate_limit(bucket_key, rule, tokens)
    
    async def _check_distributed_rate_limit(self, 
                                            bucket_key: str, 
                                            rule: RateLimitRule, 
                                            tokens: int) -> RateLimitResult:
        """Redis-basierte distributed rate limiting"""
        lua_script = """
        local key = KEYS[1]
        local tokens_requested = tonumber(ARGV[1])
        local max_tokens = tonumber(ARGV[2])
        local refill_rate = tonumber(ARGV[3])
        local now = tonumber(ARGV[4])
        
        local bucket = redis.call('HMGET', key, 'tokens', 'last_refill')
        local tokens = tonumber(bucket[1]) or max_tokens
        local last_refill = tonumber(bucket[2]) or now
        
        -- Refill tokens based on elapsed time
        local elapsed = now - last_refill
        local tokens_to_add = elapsed * refill_rate
        tokens = math.min(max_tokens, tokens + tokens_to_add)
        
        if tokens >= tokens_requested then
            -- Allow request
            tokens = tokens - tokens_requested
            redis.call('HMSET', key, 'tokens', tokens, 'last_refill', now)
            redis.call('EXPIRE', key, 3600)  -- 1 hour TTL
            return {1, tokens, now + (1/refill_rate)}
        else
            -- Deny request
            redis.call('HMSET', key, 'tokens', tokens, 'last_refill', now)
            redis.call('EXPIRE', key, 3600)
            local retry_after = (tokens_requested - tokens) / refill_rate
            return {0, tokens, now + retry_after}
        end
        """
        
        try:
            result = await self.redis_client.eval(
                lua_script,
                1,  # Number of keys
                f"rate_limit:{bucket_key}",
                tokens,
                rule.max_tokens,
                rule.requests_per_second,
                time.time()
            )
            
            allowed = bool(result[0])
            tokens_remaining = int(result[1])
            reset_time = float(result[2])
            
            return RateLimitResult(
                allowed=allowed,
                tokens_remaining=tokens_remaining,
                reset_time=reset_time,
                retry_after=reset_time - time.time() if not allowed else None
            )
            
        except Exception as e:
            logger.error(f"Distributed rate limit check failed: {e}")
            # Fallback auf lokale Rate Limiting
            return await self._check_local_rate_limit(bucket_key, rule, tokens)
    
    async def _check_local_rate_limit(self, 
                                      bucket_key: str, 
                                      rule: RateLimitRule, 
                                      tokens: int) -> RateLimitResult:
        """Lokale Token Bucket Rate Limiting"""
        if bucket_key not in self.local_buckets:
            self.local_buckets[bucket_key] = TokenBucket(rule)
        
        bucket = self.local_buckets[bucket_key]
        allowed, remaining, reset_time = bucket.try_consume(tokens)
        
        result = RateLimitResult(
            allowed=allowed,
            tokens_remaining=remaining,
            reset_time=reset_time
        )
        
        if not allowed:
            result.retry_after = reset_time - time.time()
            result.backoff_duration = bucket.get_backoff_duration()
        
        return result
    
    async def wait_for_rate_limit(self, rule_name: str, client_id: Optional[str] = None) -> float:
        """
        Wartet bis Rate Limit erfüllt ist
        
        Args:
            rule_name: Rate-Limiting Regel Name
            client_id: Optional Client-ID
            
        Returns:
            Wartedauer in Sekunden
        """
        start_time = time.time()
        
        while True:
            result = await self.check_rate_limit(rule_name, 1, client_id)
            
            if result.allowed:
                wait_time = time.time() - start_time
                if wait_time > 0.1:  # Log nur bei signifikanter Wartezeit
                    logger.debug(f"Rate limit wait completed for {rule_name}: {wait_time:.2f}s")
                return wait_time
            
            # Warte basierend auf retry_after oder backoff_duration
            wait_duration = result.retry_after or result.backoff_duration or 1.0
            wait_duration = min(wait_duration, 30.0)  # Max 30s wait
            
            await asyncio.sleep(wait_duration)
    
    def add_custom_rule(self, rule: RateLimitRule):
        """
        Fügt custom Rate-Limiting Regel hinzu
        
        Args:
            rule: RateLimitRule Definition
        """
        self._rules[rule.name] = rule
        self.local_buckets[rule.name] = TokenBucket(rule)
        logger.info(f"Custom rate limit rule added: {rule.name} ({rule.requests_per_minute}/min)")
    
    def get_rule_stats(self, rule_name: str) -> Optional[Dict[str, any]]:
        """
        Returns Statistiken für Rate-Limiting Regel
        
        Args:
            rule_name: Regel Name
            
        Returns:
            Stats Dictionary oder None
        """
        if rule_name not in self._rules:
            return None
            
        rule = self._rules[rule_name]
        bucket = self.local_buckets.get(rule_name)
        
        if not bucket:
            return None
        
        return {
            'rule_name': rule.name,
            'requests_per_minute': rule.requests_per_minute,
            'max_tokens': rule.max_tokens,
            'current_tokens': bucket.tokens,
            'consecutive_denials': bucket.consecutive_denials,
            'last_refill': bucket.last_refill,
            'strategy': rule.strategy.value,
            'priority': rule.priority
        }
    
    def get_all_stats(self) -> Dict[str, Dict[str, any]]:
        """Returns Statistiken für alle Rate-Limiting Regeln"""
        return {
            name: self.get_rule_stats(name)
            for name in self._rules.keys()
            if self.get_rule_stats(name) is not None
        }

# Globale Rate Limiter Service Instanz
_rate_limiter: Optional[RateLimiterService] = None

async def get_rate_limiter() -> RateLimiterService:
    """
    Singleton für globalen Rate Limiter Service
    
    Returns:
        RateLimiterService Instanz
    """
    global _rate_limiter
    if _rate_limiter is None:
        _rate_limiter = RateLimiterService()
        try:
            await _rate_limiter.initialize()
        except Exception as e:
            logger.warning(f"Failed to initialize distributed rate limiter: {e}")
            # Fallback auf lokale Rate Limiting
            pass
    return _rate_limiter

@asynccontextmanager
async def rate_limited_operation(rule_name: str, client_id: Optional[str] = None):
    """
    Context Manager für rate-limited Operationen
    
    Args:
        rule_name: Rate-Limiting Regel Name
        client_id: Optional Client-ID
        
    Example:
        async with rate_limited_operation('alpha_vantage') as limiter:
            # Operation wird ausgeführt wenn Rate Limit erlaubt
            response = await api_call()
    """
    rate_limiter = await get_rate_limiter()
    await rate_limiter.wait_for_rate_limit(rule_name, client_id)
    
    try:
        yield rate_limiter
    finally:
        # Rate limiting ist bereits durch wait_for_rate_limit erledigt
        pass

async def check_api_rate_limit(provider: str, tokens: int = 1) -> RateLimitResult:
    """
    Convenience-Funktion für API Rate-Limiting
    
    Args:
        provider: API Provider Name
        tokens: Anzahl Tokens
        
    Returns:
        RateLimitResult
    """
    rate_limiter = await get_rate_limiter()
    return await rate_limiter.check_rate_limit(provider, tokens)

async def wait_for_api_rate_limit(provider: str) -> float:
    """
    Convenience-Funktion für API Rate-Limiting Wait
    
    Args:
        provider: API Provider Name
        
    Returns:
        Wartedauer in Sekunden
    """
    rate_limiter = await get_rate_limiter()
    return await rate_limiter.wait_for_rate_limit(provider)

if __name__ == "__main__":
    # Test des Rate Limiting Systems
    import asyncio
    
    async def test_rate_limiting():
        print("Testing Rate Limiting System...")
        
        # Initialisiere Rate Limiter
        rate_limiter = RateLimiterService()
        
        # Test Alpha Vantage Rate Limiting (5/min = sehr restriktiv)
        print("\n=== Alpha Vantage Rate Limiting Test ===")
        for i in range(10):
            result = await rate_limiter.check_rate_limit('alpha_vantage')
            print(f"Request {i+1}: {'ALLOWED' if result.allowed else 'DENIED'} "
                  f"(Tokens: {result.tokens_remaining}, "
                  f"Retry: {result.retry_after:.1f}s)" if not result.allowed else f"(Tokens: {result.tokens_remaining})")
        
        # Test IEX Cloud mit höherer Rate
        print("\n=== IEX Cloud Rate Limiting Test ===")  
        for i in range(5):
            result = await rate_limiter.check_rate_limit('iex_cloud')
            print(f"Request {i+1}: {'ALLOWED' if result.allowed else 'DENIED'} "
                  f"(Tokens: {result.tokens_remaining})")
        
        # Rate Limiter Stats
        print("\n=== Rate Limiter Statistics ===")
        stats = rate_limiter.get_all_stats()
        for rule_name, rule_stats in stats.items():
            if rule_stats:
                print(f"{rule_name}: {rule_stats['current_tokens']}/{rule_stats['max_tokens']} tokens, "
                      f"Denials: {rule_stats['consecutive_denials']}")
    
    asyncio.run(test_rate_limiting())