#!/usr/bin/env python3
"""
Unified Import System Migration Script - Issue #57
===================================================

Migriert alle Services von sys.path.insert() Anti-Patterns zu Standard Import Manager.
Eliminiert Import Hell und standardisiert Dependency Management.

Clean Architecture Compliance:
- Single Responsibility: Import Management Migration
- Open/Closed: Erweiterbar für neue Services
- Dependency Inversion: Abstract Import Interface

Author: Generated by Claude Code - Issue #57
Date: 2025-08-28
"""

import os
import sys
import re
import shutil
from pathlib import Path
from typing import Dict, List, Tuple, Optional
from dataclasses import dataclass
from datetime import datetime

@dataclass
class ServiceMigration:
    """Service Migration Configuration"""
    name: str
    main_file: str
    sys_path_patterns: List[str]
    has_standard_import_manager: bool = False
    migration_status: str = "pending"

class UnifiedImportSystemMigrator:
    """
    Unified Import System Migration Tool
    
    Migriert alle Services systematisch:
    1. Identifiziert sys.path.insert() Anti-Patterns
    2. Ersetzt durch StandardImportManager calls
    3. Validiert Import Resolution
    4. Erstellt Backup vor Migration
    """
    
    def __init__(self, project_root: str = "/home/mdoehler/aktienanalyse-ökosystem"):
        self.project_root = Path(project_root)
        self.services_dir = self.project_root / "services"
        self.shared_dir = self.project_root / "shared"
        self.backup_dir = self.project_root / f"migration_backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        self.migration_report = []
        
        # Services mit sys.path.insert() Anti-Patterns (aus Grep-Analyse)
        self.target_services = [
            ServiceMigration("broker-gateway-service", "main.py", 
                           ["sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))"]),
            ServiceMigration("intelligent-core-service", "main.py",
                           ["sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))"]),
            ServiceMigration("ml-analytics-service", "main.py",
                           ["sys.path.insert(0, project_root)"]),
            ServiceMigration("ml-analytics-service", "main_clean_architecture.py",
                           ["sys.path.insert(0, project_root)"]),
            ServiceMigration("event-bus-service", "event_bus_daemon_v6_2_robust.py",
                           ["sys.path.insert(0, '/opt/aktienanalyse-ökosystem')",
                            "sys.path.insert(0, '/opt/aktienanalyse-ökosystem/shared')"]),
            ServiceMigration("event-bus-service", "event_bus_daemon_v6_2_0_fixed.py",
                           ["sys.path.insert(0, '/opt/aktienanalyse-ökosystem')",
                            "sys.path.insert(0, '/opt/aktienanalyse-ökosystem/shared')"]),
            ServiceMigration("event-bus-service", "infrastructure/health/postgres_health_check_pooled.py",
                           ["sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../../../../'))"]),
            ServiceMigration("frontend-service", "deploy_unified_production_8080.py",
                           ["sys.path.insert(0, str(self.service_dir))"])
        ]
    
    def create_backup(self) -> bool:
        """Erstelle vollständiges Backup aller betroffenen Services"""
        try:
            print(f"Creating backup in {self.backup_dir}...")
            self.backup_dir.mkdir(exist_ok=True)
            
            for service in self.target_services:
                service_path = self.services_dir / service.name
                if service_path.exists():
                    backup_service_path = self.backup_dir / service.name
                    shutil.copytree(service_path, backup_service_path, dirs_exist_ok=True)
                    print(f"✓ Backed up {service.name}")
            
            return True
        except Exception as e:
            print(f"✗ Backup failed: {e}")
            return False
    
    def analyze_current_imports(self) -> Dict[str, Dict]:
        """Analysiere aktuelle Import-Patterns in allen Services"""
        analysis = {}
        
        for service in self.target_services:
            service_path = self.services_dir / service.name / service.main_file
            if service_path.exists():
                try:
                    with open(service_path, 'r', encoding='utf-8') as f:
                        content = f.read()
                    
                    # Check für sys.path.insert patterns
                    sys_path_matches = re.findall(r'sys\.path\.insert\([^)]+\)', content)
                    
                    # Check für StandardImportManager
                    has_standard_manager = 'StandardImportManager' in content
                    
                    analysis[f"{service.name}/{service.main_file}"] = {
                        'sys_path_patterns': sys_path_matches,
                        'has_standard_manager': has_standard_manager,
                        'file_size': len(content.split('\n')),
                        'needs_migration': len(sys_path_matches) > 0 and not has_standard_manager
                    }
                    
                except Exception as e:
                    analysis[f"{service.name}/{service.main_file}"] = {
                        'error': str(e)
                    }
        
        return analysis
    
    def generate_standard_import_header(self) -> str:
        """Generiere Standard Import Header für alle Services"""
        return '''#!/usr/bin/env python3

# Import Management - Standard Import Manager v1.0.0 (Issue #57)
import os
import sys
from pathlib import Path

# Add project root to path (temporary for import manager loading)
project_root = str(Path(__file__).parent.parent.parent)
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# Initialize Standard Import Manager
from shared.standard_import_manager_v1_0_0_20250824 import StandardImportManager
import_manager = StandardImportManager()
import_manager.setup_imports()

# Remove temporary path modification (Clean Architecture)
if project_root in sys.path:
    sys.path.remove(project_root)

'''
    
    def migrate_service_file(self, service: ServiceMigration) -> bool:
        """Migriere einzelne Service-Datei zu Standard Import Manager"""
        service_file = self.services_dir / service.name / service.main_file
        
        if not service_file.exists():
            print(f"✗ Service file not found: {service_file}")
            return False
        
        try:
            # Read current content
            with open(service_file, 'r', encoding='utf-8') as f:
                content = f.read()
            
            # Skip if already using StandardImportManager
            if 'StandardImportManager' in content and 'setup_imports()' in content:
                print(f"✓ {service.name}/{service.main_file} already uses Standard Import Manager")
                service.migration_status = "already_migrated"
                return True
            
            # Remove sys.path.insert patterns
            modified_content = content
            for pattern in service.sys_path_patterns:
                # Escape special regex characters
                escaped_pattern = re.escape(pattern)
                # Match the exact pattern with optional whitespace
                regex_pattern = rf'^\s*{escaped_pattern}\s*$'
                modified_content = re.sub(regex_pattern, '', modified_content, flags=re.MULTILINE)
            
            # Find shebang and insert standard import header after it
            lines = modified_content.split('\n')
            insert_index = 0
            
            # Find insertion point (after shebang and docstring)
            for i, line in enumerate(lines):
                if line.startswith('#!'):
                    insert_index = i + 1
                    break
            
            # Skip docstring if present
            if insert_index < len(lines) and lines[insert_index].strip().startswith('"""'):
                in_docstring = True
                for i in range(insert_index + 1, len(lines)):
                    if '"""' in lines[i]:
                        insert_index = i + 1
                        break
            
            # Insert standard import header
            standard_header_lines = self.generate_standard_import_header().strip().split('\n')
            
            # Merge content
            new_lines = (
                lines[:insert_index] +
                [''] +  # Empty line before import section
                standard_header_lines +
                [''] +  # Empty line after import section
                lines[insert_index:]
            )
            
            # Clean up multiple empty lines
            final_content = '\n'.join(new_lines)
            final_content = re.sub(r'\n\n\n+', '\n\n', final_content)
            
            # Write migrated content
            with open(service_file, 'w', encoding='utf-8') as f:
                f.write(final_content)
            
            print(f"✓ Migrated {service.name}/{service.main_file}")
            service.migration_status = "migrated"
            
            self.migration_report.append({
                'service': service.name,
                'file': service.main_file,
                'patterns_removed': len(service.sys_path_patterns),
                'timestamp': datetime.now().isoformat()
            })
            
            return True
            
        except Exception as e:
            print(f"✗ Migration failed for {service.name}/{service.main_file}: {e}")
            service.migration_status = f"failed: {e}"
            return False
    
    def migrate_all_services(self) -> bool:
        """Migriere alle Services zu Unified Import System"""
        print("Starting Unified Import System Migration (Issue #57)...")
        print("=" * 60)
        
        # Create backup first
        if not self.create_backup():
            return False
        
        # Analyze current state
        print("\nAnalyzing current import patterns...")
        analysis = self.analyze_current_imports()
        
        for file_path, info in analysis.items():
            if info.get('needs_migration'):
                print(f"📋 {file_path}: {len(info['sys_path_patterns'])} patterns to migrate")
        
        # Perform migrations
        print("\nPerforming migrations...")
        success_count = 0
        
        for service in self.target_services:
            if self.migrate_service_file(service):
                success_count += 1
        
        # Generate report
        print("\n" + "=" * 60)
        print("MIGRATION SUMMARY")
        print("=" * 60)
        print(f"Services processed: {len(self.target_services)}")
        print(f"Successfully migrated: {success_count}")
        print(f"Failed: {len(self.target_services) - success_count}")
        print(f"Backup created: {self.backup_dir}")
        
        return success_count == len(self.target_services)
    
    def create_migration_test_suite(self) -> str:
        """Erstelle Unit Test Suite für Migration Validation"""
        test_content = '''#!/usr/bin/env python3
"""
Unified Import System Migration Test Suite - Issue #57
======================================================

Validiert die Migration zu Standard Import Manager:
1. Import Resolution funktioniert
2. Keine sys.path.insert() Anti-Patterns
3. StandardImportManager ordnungsgemäß initialisiert

Coverage Target: >=80%
"""

import unittest
import sys
import os
from pathlib import Path
import importlib.util

class UnifiedImportSystemTest(unittest.TestCase):
    """Test Suite für Unified Import System Migration"""
    
    def setUp(self):
        self.project_root = Path(__file__).parent.parent.parent
        self.services_dir = self.project_root / "services"
        
    def test_no_sys_path_insert_patterns(self):
        """Validiere dass keine sys.path.insert() Anti-Patterns vorhanden sind"""
        violations = []
        
        for service_dir in self.services_dir.iterdir():
            if service_dir.is_dir():
                for py_file in service_dir.rglob("*.py"):
                    with open(py_file, 'r', encoding='utf-8', errors='ignore') as f:
                        content = f.read()
                        if 'sys.path.insert' in content:
                            violations.append(str(py_file.relative_to(self.project_root)))
        
        self.assertEqual([], violations, 
                        f"Found sys.path.insert() anti-patterns in: {violations}")
    
    def test_standard_import_manager_usage(self):
        """Validiere StandardImportManager Verwendung in Services"""
        target_services = [
            "broker-gateway-service/main.py",
            "intelligent-core-service/main.py", 
            "ml-analytics-service/main.py",
            "event-bus-service/event_bus_daemon_v6_2_robust.py"
        ]
        
        for service_file in target_services:
            full_path = self.services_dir / service_file
            if full_path.exists():
                with open(full_path, 'r', encoding='utf-8') as f:
                    content = f.read()
                    
                self.assertIn('StandardImportManager', content,
                            f"{service_file} should use StandardImportManager")
                self.assertIn('setup_imports()', content,
                            f"{service_file} should call setup_imports()")
    
    def test_import_resolution_functionality(self):
        """Teste dass Import Resolution nach Migration funktioniert"""
        # Test Standard Import Manager kann geladen werden
        spec = importlib.util.spec_from_file_location(
            "standard_import_manager",
            self.project_root / "shared" / "standard_import_manager_v1_0_0_20250824.py"
        )
        self.assertIsNotNone(spec, "StandardImportManager module should be loadable")
        
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        
        # Test StandardImportManager Klasse existiert
        self.assertTrue(hasattr(module, 'StandardImportManager'),
                       "StandardImportManager class should exist")
        
        # Test Instanziierung funktioniert
        manager = module.StandardImportManager()
        self.assertIsNotNone(manager, "StandardImportManager should be instantiable")

if __name__ == '__main__':
    unittest.main()
'''
        return test_content

def main():
    """Main Migration Execution"""
    migrator = UnifiedImportSystemMigrator()
    
    print("UNIFIED IMPORT SYSTEM MIGRATION - ISSUE #57")
    print("==========================================")
    print("Eliminating sys.path.insert() anti-patterns across all services")
    print("Implementing Standard Import Manager for Clean Architecture")
    print()
    
    success = migrator.migrate_all_services()
    
    # Create test suite
    test_file = migrator.project_root / "tests" / "test_unified_import_system_migration.py"
    test_file.parent.mkdir(exist_ok=True)
    with open(test_file, 'w', encoding='utf-8') as f:
        f.write(migrator.create_migration_test_suite())
    
    print(f"\nTest suite created: {test_file}")
    
    if success:
        print("\n🎉 UNIFIED IMPORT SYSTEM MIGRATION COMPLETED SUCCESSFULLY!")
        print("All services now use StandardImportManager for Clean Architecture compliance.")
    else:
        print("\n⚠️  MIGRATION PARTIALLY COMPLETED - Check individual service status")
    
    return success

if __name__ == "__main__":
    main()